CoreBoost/Areas/Admin/Controllers/ArticleController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CoreBoost.Application.Interfaces;
using CoreBoost.Application.ViewModels.Article;
using CoreBoost.Data.EF;
using CoreBoost.Data.Enums;
using CoreBoost.Data.IRepositories;
using CoreBoost.Models;
using CoreBoost.Models.ArticleViewModels;

namespace CoreBoost.Areas.Admin.Controllers
{
    public class ArticleController : BaseController
    {
        private IArticleService _articleService;
        private IArticleRepository _articleRepository;

        public CoreBoostContext _context;

        public ArticleController(IArticleService articleService, IArticleRepository articleRepository, CoreBoostContext context)
        {
            _articleService = articleService;
            _articleRepository = articleRepository;
            _context = context;
        }

        public async Task<IActionResult> Browse(int? categoryId, string keyword, int? status, int? page, int? pageSize)
        {
            var fanpages = await _articleService.GetAllPagingAsync(categoryId, keyword, status, page, pageSize);
            
            ViewBag.AllCount = await _articleRepository.FindAll().CountAsync();
            ViewBag.ActiveCount = await _articleRepository.FindAll(f => f.Status == ArticleStatus.Published).CountAsync();
            ViewBag.InActiveCount = await _articleRepository.FindAll(
                f => f.Status == ArticleStatus.Draft && f.Status == ArticleStatus.Hidden
            ).CountAsync();

            return View(fanpages);
        }

        public async Task<IActionResult> Add()
        {
            ViewData["Title"] = "Thêm Bài Viết";

            ViewBag.ArticleCategories = await _context.ArticleCategories.Select(ac => new SelectListItem() {
                Value = ac.Id.ToString(),
                Text = ac.Name
            })
            .ToListAsync();
            return View();
        }

        [HttpPost]
        public IActionResult Add(ArticleViewModel articleViewModel)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return new BadRequestObjectResult(allErrors);
            }
            else
            {
                _articleService.Add(articleViewModel);
                _articleService.Save();
                return RedirectPermanent("/admin/article/browse");
            }
        }

        [HttpPost]
        public IActionResult AddAndContinue(ArticleViewModel articleViewModel)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return new BadRequestObjectResult(allErrors);
            }
            else
            {
                _articleService.Add(articleViewModel);
                _articleService.Save();
                return Redirect("/admin/article/add");
            }
        }

        public async Task<IActionResult> Edit(int id)
        {
            var model = await _articleService.GetByIdAsync(id);

            ViewData["Title"] = "Chỉnh Sửa Bài Viết";
            ViewBag.ArticleCategories = await _context.ArticleCategories.Select(ac => new SelectListItem() {
                Value = ac.Id.ToString(),
                Text = ac.Name
            })
            .ToListAsync();

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(ArticleViewModel articleViewModel)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return new BadRequestObjectResult(allErrors);
            }
            else
            {
                _articleService.Update(articleViewModel);
                _articleService.Save();
                return Redirect("/admin/article/browse");
            }
        }

        #region AJAX API

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var model = await _articleService.GetAllAsync();
            return new OkObjectResult(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetAllPaging(int? categoryId, string keyword, int? status, int? page, int? pageSize)
        {
            var model = await _articleService.GetAllPagingAsync(categoryId, keyword, status, page, pageSize);
            return new OkObjectResult(model);
        }

        [HttpGet]
        public async Task<IActionResult> GetAllStatusCount() 
        {
            ArticleCountViewModel articleCount = new ArticleCountViewModel();
            articleCount.All = await _articleRepository.FindAll().CountAsync();
            articleCount.Active = await _articleRepository.FindAll(a => a.Status == ArticleStatus.Published).CountAsync();
            articleCount.InActive = await _articleRepository.FindAll(
                a => a.Status == ArticleStatus.Draft && a.Status == ArticleStatus.Hidden
            ).CountAsync();

            return new OkObjectResult(articleCount);
        }

        [HttpGet]
        public async Task<IActionResult> GetById(int id)
        {
            var model = await _articleService.GetByIdAsync(id);
            return new OkObjectResult(model);
        }

        [HttpPost]
        public IActionResult SaveEntity(ArticleViewModel articleViewModel)
        {
            if (!ModelState.IsValid)
            {
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                return new BadRequestObjectResult(allErrors);
            }
            else
            {
                if (articleViewModel.Id == 0)
                {
                    _articleService.Add(articleViewModel);
                }
                else
                {
                    _articleService.Update(articleViewModel);
                }
                _articleService.Save();
                return new OkObjectResult(articleViewModel);
            }
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (!ModelState.IsValid)
            {
                return new BadRequestObjectResult(ModelState);
            }
            else
            {
                _articleService.Delete(id);
                _articleService.Save();
                return new OkObjectResult(id);
            }
        }

        [HttpPost]
        public IActionResult DeleteRange(List<int> idList)
        {
            if (!ModelState.IsValid)
            {
                return new BadRequestObjectResult(ModelState);
            }
            else if (idList.Count == 0)
            {
                return new BadRequestObjectResult(ModelState);
            }
            else
            {
                _articleService.DeleteRange(idList);
                _articleService.Save();
                return new OkObjectResult(idList);
            }
        }

        #endregion AJAX API
    }
}

CoreBoost/Controllers/ArticleController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CoreBoost.Application.Interfaces;

namespace CoreBoost.Controllers
{
    [Route("article")]
    public class ArticleController : Controller
    {
        private IArticleService _articleService;

        public ArticleController(IArticleService articleService)
        {
            _articleService = articleService;
        }

        [Route("all")]
        public async Task<IActionResult> All(int? categoryId, string keyword, int? status, int? page, int? pageSize)
        {
            var articles = await _articleService.GetAllPagingAsync(categoryId, keyword, status, page, pageSize);

            ViewData["Title"] = "Tất Cả Tin Tức";
            ViewData["Description"] = "Let's hype your bussiness!";
            ViewData["Keywords"] = "venthusiam, agency, marketing, phần mềm, tư vấn";

            return View(articles);
        }

        [Route("{slug}")]
        public async Task<IActionResult> Detail(string slug)
        {
            var article = await _articleService.GetBySlugAsync(slug);

            ViewData["Title"] = article.Title;
            ViewData["Description"] = article.Excerpt;
            ViewData["Keywords"] = article.Keywords;

            return View(article);
        }
    }
}

CoreBoost/Controllers/Components/RecommendedArticlesViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CoreBoost.Application.Interfaces;
using CoreBoost.Data.EF;

namespace VEenthusiam.Controllers.Components
{
    public class RecommendedArticlesViewComponent : ViewComponent
    {
        private IArticleService _articleService;

        public RecommendedArticlesViewComponent(IArticleService articleService)
        {
            _articleService = articleService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var articles = await _articleService.GetLastestAsync(3);
            return View(articles);
        }
    }
}

CoreBoost/Views/Article/All.cshtml
@model CoreBoost.Utilities.Dtos.PagedResult<CoreBoost.Application.ViewModels.Article.ArticleViewModel>

<section class="landing-section">
    <div class="landing-section__overlay">
        <div class="landing-section__overlay__wrapper">
            <p class="landing-section__subtitle">Tin Tức</p>
            <h1 class="landing-section__title">Tất Cả</h1>
        </div>
    </div>
</section>

<section class="description-section">
    <svg class="description-section__graphic" x="0px" y="0px" viewBox="0 0 1000 63">
        <polygon points="324.3,61.3 0,20.9 0,21.3 0,75.2 1000,75.2 1000,9.4 999.6,9 "></polygon>
    </svg>

    <div class="description-section__middle">
        <div class="description-section__middle__wrap">
        </div>
    </div>

    <svg class="description-section__graphic" x="0px" y="0px" viewBox="0 0 1000 68">
        <polygon points="0,-0.8 0,25.3 0,24.9 324.3,65.4 999.6,13.1 1000,13.5 1000,-0.8 "></polygon>
    </svg>

    <svg class="description-section__triangle" x="0px" y="0px" viewBox="0 0 1000 60">
        <polygon points="0,60 590,0 0,0 "></polygon>
    </svg>
</section>

<section class="articles-section">
    <div class="general-container">
        @foreach (var article in @Model.Results) {
            <article class="article">
                <div class="columns">
                    <div class="column is-4">
                        <figure class="image">
                            <img src="@Url.Content("~/")@article.ImageUrl" alt="@article.Title">
                        </figure>
                    </div>
                    <div class="column">
                        <h3 class="article__title">
                            <a href="@Url.Content("~/article/")@article.Slug">@article.Title</a>
                        </h3>
                        <p class="article__excerpt">@article.Excerpt</p>
                        <a class="article__view-btn" href="@Url.Content("~/article/")@article.Slug">Xem Thêm</a>
                    </div>
                </div>
            </article>
        }
    </div>
</section>

CoreBoost/Views/Article/Detail.cshtml
@model CoreBoost.Application.ViewModels.Article.ArticleViewModel

@{
Layout = "ArticleDetailLayout";
}

@if (@Model.ImageUrl != null) {
    <div class="image article__image" style="background-image: url('@Model.ImageUrl');"></div>
}

<div class="article-wrapper">
    <div class="columns">
        <div class="column">
            <h1 class="article-detail-main__title">@Model.Title</h1>
            <div class="article-detail-main__meta-wrapper">
                <time>@Model.DateCreated.ToString("dd-MM-yyyy")</time>
                @if (@Model.ArticleCategory != null) {
                    @Model.ArticleCategory.Name
                }
            </div>

            <article class="content article-detail-main__content">
                @Html.Raw(@Model.Content)
            </article>

            <div class="">
                <p>Từ khoá: @Model.Keywords</p>
            </div>
        </div>
    </div>
</div>

<div class="general-container">
    @await Component.InvokeAsync("RecommendedArticles")
</div>